#!/usr/local/bin/expect --

set login_id "terzeron"
stty -echo
set passwd "micro575"
stty echo
puts "\r"
set nick ""
set hangul ""
set term ""
set boardname "CnUnix"

spawn ssh kids@kids.kornet.net
trap { puts "TELNET CLOSED.\r"; exit } SIGCHLD

proc login { loginname password nick hangul term boardname} {
	# for telnet connection
	#expect "login: kids" { send "kids\r" }
	
	# for ssh connection
	expect "사용자명(User  Id): " { send "$loginname\r" }
	if {$loginname=="guest"} {
		# guest 인 경우 다르게...
		expect "I Am" {send "$nick\r"}
		expect "Y / n" {send "$hangul\r"}
		expect "dumb" {send "$term\r"}
	} else {
		# 일반 유저인 경우 ...
		expect "비밀번호(Password):" { 
			send "$password\r"
		}
	}
	set timeout 1
	expect -re "다른쪽 접속을 쫓아낼까요" {
		send "y\r"
		expect -re "키를 치십시오" {
			send "\r"
		}
	} 
	set timeout -1
	expect -re "이전글" {
		send "\r"
	}
	expect -re "Kids 종료" {
		send "a\r"
	}


